### ISSUE TITLE
Consider how a second column can be created within the event info without relying on templates

### ISSUE THREAD

**Issue by alexandtheweb** [alexandtheweb/uxbrighton-prototype#9]
Using markdown alone, can we tell certain parts of the content to flow into the second column? Investigate

**Comment by alexandtheweb** [comment]
Marking this as closed for now due to [the following Jekyll issue thread](https://github.com/jekyll/jekyll/issues/246)

Tread suggests either relying on an include to accomplish this (we already sort of do this, via static content in the page template) or using YAML front matter to break the content up into sections.

**Comment by kbrock** [comment]
@alexandtheweb If you are using kramdown, you may be able to use [attribute lists](http://kramdown.gettalong.org/syntax.html#inline-attribute-lists)

All depends upon your use case. GL
